services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  redis-commander:
    image: rediscommander/redis-commander
    platform: linux/amd64
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379