"""Add id column to quote_list table

Revision ID: 9f6c9e281437
Revises: 
Create Date: 2025-06-11 12:44:34.948651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6c9e281437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    with op.batch_alter_table('quote_list', schema=None) as batch_op:
        # 1. Add new columns as nullable
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))

    conn = op.get_bind()
    # 2. Copy data from old columns to new columns
    conn.execute(sa.text('UPDATE quote_list SET content = "Quote"'))
    conn.execute(sa.text('UPDATE quote_list SET author = "Author"'))

    # 3. Create a sequence and populate id
    conn.execute(sa.text('CREATE SEQUENCE quote_list_id_seq OWNED BY quote_list.id'))
    conn.execute(sa.text('UPDATE quote_list SET id = nextval(\'quote_list_id_seq\')'))

    # 4. Set id as NOT NULL and PK, drop old columns
    with op.batch_alter_table('quote_list', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('content', existing_type=sa.Text(), nullable=False)
        batch_op.alter_column('author', existing_type=sa.String(length=255), nullable=False)
        batch_op.create_primary_key('pk_quote_list', ['id'])
        batch_op.drop_column('Quote')
        batch_op.drop_column('Author')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=False))
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('firebase_uid')

    with op.batch_alter_table('quote_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Quote', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('author')
        batch_op.drop_column('content')
        batch_op.drop_column('id')

    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('quotes_pkey'))
    )
    # ### end Alembic commands ###
