"""Add user memory system


Revision ID: b0babef30e02
Revises: d599456037ed
Create Date: 2025-07-10 12:49:36.800026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0babef30e02'
down_revision = 'd599456037ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_advices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memories_used_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recent_notes_used_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dominant_emotion', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_advices', schema=None) as batch_op:
        batch_op.drop_column('dominant_emotion')
        batch_op.drop_column('recent_notes_used_count')
        batch_op.drop_column('memories_used_count')

    # ### end Alembic commands ###
