"""add profile picture

Revision ID: cee6f377fc53
Revises: e5c78866ee74
Create Date: 2025-07-11 02:09:46.474777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee6f377fc53'
down_revision = 'e5c78866ee74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_filename')
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
