"""remove unused columns

Revision ID: e5c78866ee74
Revises: b0babef30e02
Create Date: 2025-07-10 13:25:56.764871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5c78866ee74'
down_revision = 'b0babef30e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_advices', schema=None) as batch_op:
        batch_op.drop_column('avg_neutral')
        batch_op.drop_column('of_week')
        batch_op.drop_column('avg_fear')
        batch_op.drop_column('avg_joy')
        batch_op.drop_column('avg_anger')
        batch_op.drop_column('avg_sadness')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_advices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_sadness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avg_anger', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avg_joy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avg_fear', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('of_week', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avg_neutral', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
